### ISSUE TITLE
Container and Non-Orthogonal Boxes

### ISSUE THREAD

**Issue by costrouc** [wackywendell/tess#1]
So I was checking out your wrapper to voro++ and I really like it. I was trying to find out does tess have support for non-orthogonal limits?

Best,
Chris

**Comment by costrouc** [comment]
From looking at the voro++ library it looks like your library does not have support for non-orthogonal. I am looking at your library because of it's clean interface. I do a lot of work with `pymatgen` a package for the automation of material science calculations. Their wrapper around Zeo++ and Voro++ crashes a lot so I need an alternative.

I would be happy to contribute code that uses `container_periodic_base` which will allow non orthogonal boxes. The only requirement it would enforce is that all directions are periodic.

Would this work? I'll submit a pull request this week

**Comment by wackywendell** [comment]
Yes, that would be great! As long as it does not diminish current working features, a pull request would be welcome.

**Comment by costrouc** [comment]
Great I will have a pull request shortly.

**Comment by WeiLiPenguin** [comment]
> Great I will have a pull request shortly.

any news ?

**Comment by costrouc** [comment]
See my PR https://github.com/wackywendell/tess/pull/2 it was never merged..
