### ISSUE TITLE
Expose voro++'s support for "walls"

### ISSUE THREAD

**Issue by estan** [wackywendell/tess#3]
I was happy to find `tess` since I'm working on a C++ project using voro++, and would possibly like to switch to Python. However, I need support for voro++'s concept of "wall". See the `voro::wall` pure virtual class and its subclasses.

For my use case, I'd want to make a custom wall (so deriving `voro::wall`).

Would be great if this could be exposed in `tess` at some point.

**Comment by wackywendell** [comment]
Hi @estan!

This is a very delayed reply, but looking at this now... I'm not sure how possible this would be from Python - `wall` implementations may need to be in C++. If it were possible, its well outside the scope of my purposes to implement. The simplest solution would probably be to fork this repo, add your own wall implementation in c++, add support for it to `_voro.pyx`, and go from there.
